### ISSUE TITLE
A question about string formatting

### ISSUE THREAD

**Issue by phozzy** [Olical/dotfiles#10]
Hello!
Could you please explain, how does this line work?
https://github.com/Olical/dotfiles/blob/bf1d72d37ea87c63a3a5eeee9ef948eff78aae26/stowed/.config/nvim/init.lua#L13
I can see here only 2 "%s" placeholder for strings, and 3 strings (pack_path, repo, repo) that you want to place there. Is it intentional?
Thanks!

**Comment by Olical** [comment]
Just a typo by the looks of it, the second `repo` will be ignored. It's not required but it also doesn't really harm anything.
