### ISSUE TITLE
A licence for your config files

### ISSUE THREAD

**Issue by phozzy** [Olical/dotfiles#11]
Hello!
I want to almost copy and paste your https://github.com/Olical/dotfiles/blob/master/stowed/.config/nvim/init.lua file.
What license does it have? Should I mention you in comments for my config that I'm going to create?

**Comment by Olical** [comment]
Go for it, I never really thought to license dotfiles, you can consider them unlicensed (https://unlicense.org/), do what you want with anything you want. Feel free to link back if you want, it could help others in the future but I don't mind otherwise 🙂
