### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by frenchy64** [Olical/dotfiles#13]
Was randomly perusing, I'm guessing the `module` here should end with `which-key` instead of `auto-pairs`?

https://github.com/Olical/dotfiles/blob/8bbb61572065f8fa5ddb4a0dd5d3005b4265ad82/stowed/.config/nvim/fnl/dotfiles/plugin/which-key.fnl#L1

**Comment by Olical** [comment]
You're right! That'll probably only really mess with interactive evals but since the module is being required for side effects it actually works out okay. I'll get that fixed, thanks for spotting it 😄
