### ISSUE TITLE
LspConfig Out: Cannot access configuration for metadata

### ISSUE THREAD

**Issue by rafaeldelboni** [Olical/dotfiles#14]
Hey hello! As you may know I have a [very similar setup as yours](http://github.com/rafaeldelboni/nvim-fennel-lsp-conjure-as-clojure-ide) and recently I'm getting this annoying warning while evaluating and using conjure autocomplete with fennel nvim config files on conjure's log buffer :

```bash
; eval (file): /home/delboni/.dotfiles/config/nvim/fnl/config/plugin/lspconfig.fnl
; (out) [lspconfig] Cannot access configuration for metadata. Ensure this server is listed in `server_configurations.md` or added as a custom server.
; (out) [lspconfig] Cannot access configuration for aniseed/locals. Ensure this server is listed in `server_configurations.md` or added as a custom server.
; (out) [lspconfig] Cannot access configuration for metadata. Ensure this server is listed in `server_configurations.md` or added as a custom server.tree/master/stowed

...

nil
```

Do you have any idea of what I'm doing wrong?

Ps: Everything is working as intended, it just this warning that keeps showing up when editing my fennel config files.

**Comment by Olical** [comment]
I can't say I've ever seen this before 😞 it seems like it's mostly an LSP thing, maybe you need to turn off LSP specifically for Fennel?

**Comment by Olical** [comment]
Is this still an issue for you? I've still never seen it 😬

**Comment by rafaeldelboni** [comment]
No, I never got this anymore, sorry for letting this open. 🙃

**Comment by Olical** [comment]
Oh no problem! Just thought I'd check in with issues I'd forgotten about.
