### ISSUE TITLE
Investigate a better alternative to EasyMotion

### ISSUE THREAD

**Issue by Olical** [Olical/dotfiles#15]
EasyMotion has been a staple of my vimming for as long as I can remember but I would like something that uses the features Neovim has to offer. EM's way of inserting the jump marker characters actually modifies the buffer for a brief time which freaks out my linters and LSP. One that uses virtual text or floating windows + Lua would be great.

**Comment by Liverm0r** [comment]
Take a look at [lightspeed](https://github.com/ggandor/lightspeed.nvim), it's written in fennel, there is a [6-minutes-video](https://youtu.be/ESyld9NCl1w) with a show case

**Comment by Olical** [comment]
Oh yeah, I'm already using it! I forgot to close this issue. I like it so far even if I miss some parts of EasyMotion. It's growing on me!
