### ISSUE TITLE
vim.lsp.diagnostic.get_count is deprecated

### ISSUE THREAD

**Issue by Olical** [Olical/dotfiles#16]
I am getting spammed with this `vim.lsp.diagnostic.get_count is deprecated. See :h deprecated` even though my config never mentions it. Where is it coming from?

**Comment by cvoges12** [comment]
I don't know, but this is also deprecated:

https://github.com/Olical/dotfiles/blob/e14262233f8e362295f3c9ff2d4b14e25a902693/stowed/.config/nvim/fnl/dotfiles/plugin/lspconfig.fnl#L23

**Comment by cvoges12** [comment]
I'm trying to also figure out how to rewrite `vim.lsp.diagnostic.get_count` as `vim.diagnostic.get()` though. So if you figure it out, lmk

**Comment by Olical** [comment]
It was `beauwilliams/statusline.lua`, and here's the fix:

https://github.com/Olical/dotfiles/blob/c35f91edcc27587e5c53b4a82241ae81136eae83/stowed/.config/nvim/fnl/dotfiles/plugin/statusline.fnl#L4

That worked for me at least! The other one I should probably unmap too but that's less of a concern. This one was spamming me with SO many warnings.
